[colors.bright]
black = "0x696969"
blue = "0x007FFF"
cyan = "0x00CCCC"
green = "0x03C03C"
magenta = "0xFF1493"
red = "0xFF2400"
white = "0xFFFAFA"
yellow = "0xFDFF00"

[colors.normal]
black = "0x10100E"
blue = "0x0087BD"
cyan = "0x20B2AA"
green = "0x009F6B"
magenta = "0x9A4EAE"
red = "0xC40233"
white = "0xC6C6C4"
yellow = "0xFFD700"

[colors.primary]
background = "0x000000"
foreground = "0xC6C6C4"

[font]
size = 8

[font.bold]
family = "BlockZone"
style = "Regular"

[font.bold_italic]
family = "BlockZone"
style = "Regular"

[font.italic]
family = "BlockZone"
style = "Regular"

[font.normal]
family = "BlockZone"
style = "Regular"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Control"

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["new-session"]
program = "/usr/bin/tmux"
